### ISSUE TITLE
Demo Brigade at SIG App Delivery meeting

### ISSUE THREAD

**Issue by radu-matei** [cncf/sig-app-delivery#12]
Hi, everyone! We would really like the chance to demo Brigade at SIG App Delivery. 

Brigade is an in-cluster runtime that interprets scripts and executes generic pipelines of work in Kubernetes. Using JavaScript, developers can chain containers together in a script to create an event-driven workflow in Kubernetes. Scripts can define a series of jobs that run in parallel or serially, and take advantage of having full programming language support for error handling and async functionality, as well as benefit from the rich JavaScript ecosystem of libraries.

Brigade is a CNCF Sandbox project, it integrates with other cloud-native projects (Helm, Prometheus, CloudEvents, Virtual Kubelet), and has varied use cases (from a foundation for opinionated CI/CD platforms, to building training pipelines for predictive modeling, or asynchronous processing for orders).

cc @resouer, @AloisReitbauer, @bryanl 

References:
1. GitHub: [@brigadecore](https://github.com/brigadecore)
1. Documentation: [https://docs.brigade.sh](https://docs.brigade.sh)

**Comment by AloisReitbauer** [comment]
Presentation would be good. Right now Argo also submitted a request for their workflow project to join

**Comment by AloisReitbauer** [comment]
Are you still open to present?
