### ISSUE TITLE
Operator Framework/Hub for CNCF submission

### ISSUE THREAD

**Issue by AloisReitbauer** [cncf/sig-app-delivery#14]
https://github.com/cncf/toc/pull/303 - PR within the TOC repo

**Comment by erinaboyd** [comment]
@AloisReitbauer Since there was already a PR opened in the main TOC repo, can we just provide a pointer here?

**Comment by bryanl** [comment]
@amye Is there anything else we need to do here?

**Comment by amye** [comment]
With the completed review linked in [#303](https://github.com/cncf/toc/pull/303), we are good here. 
Closing.
