### ISSUE TITLE
App Delivery Review of Argo

### ISSUE THREAD

**Issue by caniszczyk** [cncf/sig-app-delivery#18]
The @cncf/toc would like to request public feedback from CNCF SIG App Delivery on Argo: https://github.com/cncf/toc/pull/299

**Comment by AloisReitbauer** [comment]
Which template should we be using?

**Comment by AloisReitbauer** [comment]
We started the due diligence doc: https://docs.google.com/document/d/1rhL9CIInKAArIVpLiabiSuNCi14sSUD_0sDUbjEWPw0/edit#

**Comment by amye** [comment]
Checking in on this for current status

**Comment by bryanl** [comment]
This should be ready to go back to the TOC.

**Comment by caniszczyk** [comment]
Thanks @bryanl and CNCF SIG App Delivery

@AloisReitbauer can you make that doc public?

**Comment by caniszczyk** [comment]
Alright, this has been reviewed by the CNCF SIG App Delivery and ready to hand back to the TOC to decide on a vote or further review thanks all
