### ISSUE TITLE
Logo Ideas

### ISSUE THREAD

**Issue by AloisReitbauer** [cncf/sig-app-delivery#20]
We are getting a logo!

Use this issue to share and discuss your ideas.

**Comment by tylerdave** [comment]
I'm envisioning a pack animal w/ bundles of different shape and size packages.

**Comment by erdong** [comment]
what about ants or bees？
Ants and bees are good at building large buildings.
Like ant nests and hives

**Comment by johnroach** [comment]
The first thing when I heard packaging for some reason was a kangaroo :)

**Comment by rajatjindal** [comment]
a bee/ant riding a kubernetes ship with containers in the background

**Comment by dmueller2001** [comment]
bee with honeycomb in background that is a rif on the kubernetes logo

**Comment by mkorbi** [comment]
a couple of ideas:

- Camel or Dromeda carrying packages
- A classic old steam train
- kind of robot handling delivery

**Comment by mark-rushakoff** [comment]
A logo that actually evokes the idea of delivering something seems more fitting for app delivery, doesn't it?

My suggestion is a wrapped gift, either plain cube/rectangular box, or a wrapped up ship's wheel like the Kubernetes logo.

If we had to stick with animals, a carrier pigeon makes me think of delivery. If not that, some kind of [pack animal](https://en.wikipedia.org/wiki/Pack_animal), so long as it is visibly carrying a pack.

**Comment by johnroach** [comment]
@mark-rushakoff I like that idea, I don't know if it is due to the holidays but can certainly see a reindeer pack animal like so https://en.wikipedia.org/wiki/Pack_animal#/media/File:Reindeer_and_pack,_with_Lapp_driver.jpg :D or again a Kangaroo with a package in its pouch.

**Comment by amye** [comment]
[SIG-App-Delivery-logos-v1.pdf](https://github.com/cncf/sig-app-delivery/files/4033150/SIG-App-Delivery-logos-v1.pdf)
A first round from our designer! 
We'll discuss at our 1/15 meeting.

**Comment by amye** [comment]
Round 2 of designs are in! 
[SIG-App-Delivery-v2.pdf](https://github.com/cncf/sig-app-delivery/files/4129021/SIG-App-Delivery-v2.pdf)

**Comment by hone** [comment]
I dislike the bird ones, because it reminds me so much of twitter.

I still really like the baby kangaroo one. It passes the "I'd want this on my laptop as a sticker" test. My second favorite is the camel one.

**Comment by rootsongjc** [comment]
![image](https://user-images.githubusercontent.com/3328185/73826770-51be8e80-4839-11ea-8c0c-619420586633.png)
This ship looks nice.

**Comment by kensipe** [comment]
top picks:  
1. Camel (row 3, col 4)
2. postal bird (row 2, col 1)
3. kangaroo (row 2, col 3)

I'm not a fan of the gift packages, ants or bees.  
happy to go with community decision... 

nice work @amye

**Comment by resouer** [comment]
![image](https://user-images.githubusercontent.com/1701782/79356091-61bab480-7ef3-11ea-89fc-36d005b097cb.png)

This one!!!

**Comment by dmueller2001** [comment]
(1) Bee on hive/grid design

**Comment by umamukkara** [comment]
A dove/bird carrying a package/container

**Comment by gerred** [comment]
I'm with @resouer. Joey is my favorite.

**Comment by mattfarina** [comment]
How about a beaver building a damn? It's aquatic. It's how we piece things together to build something bigger.

**Comment by mattfarina** [comment]
ok, for realz...

- I liked the bee in the hive one until death hornets. I still like it the most but death hornets.
- If not bee on hive I like trains.

**Comment by cdavisafc** [comment]
After looking at the logos for SIG security and SIG storage, I like the bottom, right - bee superimposed on the CNCF logo. Like it anyway, and stylistically it is consistent with those other two.

I like solidarity with bees against the death hornets!

**Comment by ishantanu** [comment]
A logo with the Bee in the last row's second column.

**Comment by amye** [comment]
![Numbered Version](https://github.com/cncf/sig-app-delivery/files/4719606/SIG-App-Delivery-v2.pdf)

Poll is open for two weeks, starts June 2, 2020; closes June 16, 2020 at 12pm Pacific.
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/1)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/1/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/2)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/2/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/3)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/3/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/4)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/4/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/5)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/5/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/6)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/6/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/7)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/7/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/8)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/8/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/9)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/9/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/10)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/10/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/11)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/11/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/12)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/12/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/13)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/13/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/14)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/14/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/15)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/15/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/16)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/16/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/17)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/17/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/18)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/18/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/19)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/19/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/20)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/20/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/21)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/21/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/22)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/22/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/23)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/23/vote)

**Comment by amye** [comment]
![SIG-App-Delivery-v3](https://user-images.githubusercontent.com/107161/83569051-c5676400-a4d8-11ea-98ad-d1e5b64837b6.png)

Poll is open for two weeks, starts June 2, 2020; closes June 16, 2020 at 12pm Pacific.
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/1)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/1/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/2)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/2/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/3)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/3/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/4)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/4/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/5)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/5/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/6)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/6/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/7)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/7/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/8)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/8/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/9)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/9/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/10)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/10/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/11)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/11/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/12)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/12/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/13)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/13/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/14)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/14/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/15)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/15/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/16)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/16/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/17)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/17/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/18)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/18/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/19)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/19/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/20)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/20/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/21)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/21/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/22)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/22/vote)
[![](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/23)](https://api.gh-polls.com/poll/01E9VCNSJ2642E99NV8GTE6JEF/23/vote)

**Comment by amye** [comment]
I'll keep this open until after the 6-17 meeting concludes for final discussion.

**Comment by amye** [comment]
21 looks like the winner, @AloisReitbauer - @resouer, @bryanl -- final thoughts?

**Comment by resouer** [comment]
@amye Looks good to me!

**Comment by bryanl** [comment]
Looking good!
