### ISSUE TITLE
SIG-App-Delivery Graduation review for Harbor

### ISSUE THREAD

**Issue by raravena80** [cncf/sig-app-delivery#24]
Harbor is proposing Graduation: https://github.com/cncf/toc/pull/311

There is a Helm specific component in Harbor that needs to be reviewed by SIG-App-Delivery.

Other relevant SIGs are reviewing (or have reviewed): SIG-Runtime, SIG-Storage, SIG-Security.

There is a consolidated document that needs to be updated once the review is complete: http://bit.ly/harbor-graduation-dd

**Comment by michmike** [comment]
@bryanl , @AloisReitbauer , @resouer ,

the harbor team has prepared a due diligence document that could aid in the review of Harbor and significantly speed up time. 
You can start here: https://docs.google.com/document/d/15gX7EeeXQThEvVMGpL-0a1mOwGuByLtMfvXNJaKT0A0/edit?usp=sharing

I also added this to your agenda for this upcoming wednesday

**Comment by michmike** [comment]
as per the CNCF sig-app-delivery meeting on 4/1/2020, @resouer will own the review of Harbor for the graduation bid. thank you Lei!

**Comment by resouer** [comment]
Happy to take Harbor project review!

I think the first action several questions about Harbor as a software distribution source we discussed in the meeting. Hope those details can be added in the DD doc.

**Comment by michmike** [comment]
@resouer we have answers to all your questions in the Due Diligence self-assessment document. I added some more context to some of them as well.
Here's the areas you asked for
1. Current Artifacts supported (covered by https://docs.google.com/document/d/15gX7EeeXQThEvVMGpL-0a1mOwGuByLtMfvXNJaKT0A0/edit#heading=h.4gccigtnbc96)
2. Software Distribution capabilities (covered by https://docs.google.com/document/d/15gX7EeeXQThEvVMGpL-0a1mOwGuByLtMfvXNJaKT0A0/edit#heading=h.8k6shnk42w0n)
3. Scalability of Harbor (covered by https://docs.google.com/document/d/15gX7EeeXQThEvVMGpL-0a1mOwGuByLtMfvXNJaKT0A0/edit#heading=h.r0hfdgftnmiz)

**Comment by resouer** [comment]
Review conclusion is added here: https://github.com/cncf/sig-app-delivery/pull/25 

We think Harbor is generally ready for next stage without further concerns.

**Comment by raravena80** [comment]
Thanks @resouer could you also update the SIG-App-Delivery part in the [consolidated review doc](http://bit.ly/harbor-graduation-dd)?

**Comment by resouer** [comment]
@raravena80 Just added.

**Comment by AloisReitbauer** [comment]
Done
