### ISSUE TITLE
[Operator WG] Finish/review Executive Summary

### ISSUE THREAD

**Issue by Jenniferstrej** [cncf/sig-app-delivery#35]

**Comment by AlexsJones** [comment]
Suggestion to slightly change this:

> Maintaining application infrastructure requires many repetitive human activities that are devoid of lasting value.
> Computers are the prefered method of performing repetitive tasks and verifying the state of an object, enabling the infrastructure requirements to be codified. An operator provides a way to encapsulate the required activities, checks and statement management of an application.
> 
> In Kubernetes, an operator provides intelligent, dynamic management capabilities by extending the functionality of the API.
> 
> These operator components allow for the automation of common processes as well as reactive applications that can continually adapt to their environment. This in turn allows for more rapid development with fewer errors, lower mean-time-to-recovery, and increased engineering autonomy.


Thoughts?

**Comment by AlexsJones** [comment]
https://github.com/cncf/sig-app-delivery/pull/106
