### ISSUE TITLE
[Operator WG] Security

### ISSUE THREAD

**Issue by Jenniferstrej** [cncf/sig-app-delivery#39]
Security section on the Operator white paper.

Sections to be discussed with Security SIG and when those are defined, create tasks under the white paper Project on Github.

Currently the suggested sections are:

Build trust - documentations

- Threats
- which threats an operator brings?
- How do users that wants to use an operator can trust it? What API endpoints and permissions?
- CVEs disclosure process
- How transparent the process is?
- Audit log analysis, what should the user expect to see once this is deployed

Security constraints - implementation

- How can I as a customer or end user of an operator can make sure that it’s a secure one?
- API Permissions
- What are the security features of the operator?
- Is this operator considering security as a first class citizen?
- Operator Scope (Cluster vs. Namespaced vs. Outside Cluster)

Metrics - end user observation:

- Audit log 

(Suggestion: Follow up: z	Follow the recommendation on Sig Security white paper for securing workloads)

**Comment by cseader** [comment]
I can have a look as a member of the Security SIG

**Comment by sublimino** [comment]
Another sig-sec person here. Happy to help and contribute some security perspectives, ControlPlane has some existing work around threats in this area we can share.

I won't be able to commit straight away due to training commitments up to the end of next week, is there any indication of your timescales please @Jenniferstrej?

**Comment by jlk** [comment]
One more from sig-sec :) happy to help out. Will give the draft a read...

**Comment by Jenniferstrej** [comment]
@sublimino - We will share the Proposed Schedule by tomorrow (cc @thschue)

**Comment by jlk** [comment]
Folks - I set up a zoom call to do some brainstorming on the topic this Thursday at 11am Pacific time. Anybody with thoughts is welcome to join!

https://us02web.zoom.us/j/88663179358?pwd=bm8zNXJtR2I0ZFlUM09ORDg4NTZ3QT09

@thschue one thought just occurred to me from previous cncf calls - Should I record the zoom call? If so, upload where?

**Comment by sublimino** [comment]
Hi @Jenniferstrej, do you know any more about the expected date here please?

Sorry to have missed the call @jlk! Definitely up for scheduling something to collaborate  : ] I'm in GMT FWIW :pray:

**Comment by jlk** [comment]
From the SIG call yesterday, they're still aiming for a draft release next week.

Cameron and I have been doing weekly calls, brainstorming and putting the chapter together. I can send you a link to the gdoc, but we're about done so my intention is to turn that into a markdown PR this weekend. Your call if you want to look at the gdoc now or wait for the PR - I'm open to comments in either place.

**Comment by sublimino** [comment]
Ah irregular attendance on my behalf, apologies! 

Gdoc is a little easier for me, gmail is sublimino.

**Comment by jlk** [comment]
@sublimino @cseader thanks for the help so far - don't forget to add your names to the contributors doc
