### ISSUE TITLE
[Operator WG] Operator Frameworks for Kubernetes (Introduction)

### ISSUE THREAD

**Issue by Jenniferstrej** [cncf/sig-app-delivery#40]
"Operator Frameworks for Kubernetes" section on Operator white paper

Description of a few most popular frameworks used to create operators. It would be best if we could get input from the framework contributors.

**Comment by feloy** [comment]
I would like to work on introducing the controller-runtime library and the kubebuilder framework in this section

**Comment by Jenniferstrej** [comment]
@feloy - can you choose a framework you will work on first and add an issue in the "Issues" tab and post it here
(e.g. Operator Framework for Kubernetes - kubebuilder)
? I will then make sure it's added to the project board/in progress. (at the moment I can't get anyone in the assignee tab it seems. I am trying to verify how I can get that).

There is a "Contributors" section on the White Paper, and you should add your name there when making a PR. Even if Github admin stops us from certain things we will absolutely make sure you are given the deserved credit. 

Please let me know if you have any questions! And thanks for contributing :)

**Comment by feloy** [comment]
I would like to document the kubebuilder framework: https://github.com/cncf/sig-app-delivery/issues/65
