### ISSUE TITLE
[Operator WG] Operator Lifecycle Management

### ISSUE THREAD

**Issue by Jenniferstrej** [cncf/sig-app-delivery#42]
"Operator Lifecycle Management" section on Operator white paper.

- Updating an Operator itself
- Updating managed CRDs

**Comment by OmerKahani** [comment]
> "Operator Lifecycle Management" section on Operator white paper.

https://github.com/cncf/sig-app-delivery/blob/master/operator-wg/whitepaper/06_Lifecycle.md
