### ISSUE TITLE
Demonstrate CNAB and Porter at sig-app-delivery meeting

### ISSUE THREAD

**Issue by jeremyrickard** [cncf/sig-app-delivery#6]
👋  

We'd love the chance to demo [Porter](https://porter.sh) and [CNAB](https://deislabs.io/cnab/) at one of the upcoming sig-app-delivery meetings. Porter is a tool for installing applications using CNAB and we thought that sig-app-delivery would be a good place to demo and discuss. We’ve been really focused on trying to deliver the best experience around CNAB and we’d love to hear feedback from this group.

We were thinking something along the lines of:
5 mins - A whirlwind introduction to CNAB
10 mins - How to build and work with bundles with Porter

We think it aligns with sig-app-delivery's goals and would love to have people check it out and contribute.

**Comment by AloisReitbauer** [comment]
As this was presented. Do you see any follow up issues on this topic?

**Comment by jeremyrickard** [comment]
I don't think so at the moment. I'll close for now. I think that there is a desire to eventually submit Porter for consideration as a sandbox project, but I don't believe that will happen currently. We're focused on building the user base up at the moment.
