### ISSUE TITLE
Keptn as CNCF Sandbox project

### ISSUE THREAD

**Issue by AloisReitbauer** [cncf/sig-app-delivery#7]
https://github.com/cncf/toc/pull/237 

https://docs.google.com/presentation/d/1k1QcjeTmb1ZeYtwMntLw1IVTbJXGerGnGExow9oa7i4/

**Comment by amye** [comment]
Is there a document around SIG-Review available for this project?

**Comment by kgamanji** [comment]
+1 to Amye's comment

**Comment by AloisReitbauer** [comment]
Review document is available here: https://docs.google.com/document/d/12Uhkv5aMnvM_HFvpYDuDTN2Zzc83qKOLYmp-k_RGWB8/edit#heading=h.kd4eg2uz3lt0
