### ISSUE TITLE
KUDO as CNCF Sandbox Project

### ISSUE THREAD

**Issue by guenter** [cncf/sig-app-delivery#8]
KUDO presented to the TOC on Sep 17 and we were referred to SIG App Delivery for another review. Can someone clarify what this review entails? I don't see the process documented anywhere publicly.

TOC issue: cncf/toc#261

**Comment by guenter** [comment]
So reading through the mailing list and the agenda it seems like the next step is another presentation to this SIG. We'd like to get on the agenda for this Wednesday. Thanks!

**Comment by guenter** [comment]
We were told that the TOC will not be reviewing new projects before KubeCon and instead focus on existing projects that are requesting reviews. Closing this for now and will open a new issue after KubeCon.

**Comment by AloisReitbauer** [comment]
There is a newer issue #22
