### ISSUE TITLE
Write an overview about metacontroller

### ISSUE THREAD

**Issue by thschue** [cncf/sig-app-delivery#84]
Give a short overview what metacontroller is and how it could help ...

**Comment by thschue** [comment]
@grzesuav will write this

**Comment by grzesuav** [comment]
hi, can do it :)

**Comment by grzesuav** [comment]
Initial version -https://github.com/cncf/sig-app-delivery/pull/86 , would appreciate any advice what is missing, what is unclear, gramas etc
