### ISSUE TITLE
Introduce and Demonstrate Litmus at sig-app-delivery meeting

### ISSUE THREAD

**Issue by umamukkara** [cncf/sig-app-delivery#9]
Litmus is a toolset to do chaos engineering in a kubernetes native way. Litmus provides chaos CRDs for Cloud-Native developers and SREs to inject, orchestrate and monitor chaos to find weaknesses in Kubernetes deployment in production. 

We would love to demonstrate Litmus at sig-app-delivery meeting.

**Proposed Agenda:**
Introduction, architecture - 15 minutes
Demo - 10 minutes
Road map - 5 minutes

**Important links:**
GitHub: https://github.com/litmuschaos
Slack: https://kubernetes.slack.com/messages/CNXNB0ZTN
Website: https://litmuschaos.io
Twitter: https://twitter.com/LitmusChaos

**Comment by umamukkara** [comment]
@AloisReitbauer

**Comment by AloisReitbauer** [comment]
We have scheduled you for presentation see agenda doc:

https://docs.google.com/document/d/1OykvqvhSG4AxEdmDMXilrupsX2n1qCSJUWwTc3I7AOs/edit#

**Comment by bryanl** [comment]
Presented on 20191023
